POST http://localhost:1010/module/forms-module/form/submit
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="form"

contact
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="code"

w274n
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key"

test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="message"

Hello world!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="from"

me@example.org
------WebKitFormBoundary7MA4YWxkTrZu0gW--
