id = "demo-site"
hostname = [ "localhost", "127.0.0.1" ]
baseurl = "http://localhost:2020"
locale = "en_US"
theme = "demo"
context_path = "/"

# ui manager application configuration
[ui]
force2fa = false                    # force 2fa for all users
managerEnabled = true               # enable the ui manager application

[ui.2fa]
mail_from = "noreply@localhost.de"
mail_sender = "CondationCMS"
mail_title = "CondationCMS: your login code"
mail_message = '''
Hello <username>,

your login code: <code>
'''

# modules to load for this site
[modules]
active = ["example-module"]         # list of active modules for this site


# translation settings
[translation]
enabled = true                      # enable translation for this site
languages = ["de", "en"]            # languages available for this site

# config mulitsite translation mapping
[[translation.mapping]]
language = "de"                     # language code for this mapping
site = "demo-de-site"               # site id for this mapping

[[translation.mapping]]
site = "demo-site"                  # site id for this mapping
language = "en"                     # language code for this mapping    