# site configuration for dev environment

hostname = [ "localhost5" ]           # hostnames for this site, used for request matching

[api]
enabled = true
whitelist = ["meta.*", "title"]

# cache configuration for this site
[cache]
content = false                        # enable content caching for this site