id = "demo-site"
hostname = [ "localhost", "127.0.0.1" ]
baseurl = "http://localhost:2020"
locale = "en_US"
theme = "demo"
context_path = "/"

[multisite]
group = "demo"


# modules to load for this site
[modules]
active = ["example-module"]         # list of active modules for this site


[index.fields.location]
type = "geo"
