id: demo-site
hostname: 
  - localhost
baseurl: "http://localhost:1010"
language: en
theme: demo
modules:
  active:
    - seo-module
media:
  formats:
    - name: small
      width: 256
      height: 256
      format: webp
      compression: true
    - name: big
      width: 512
      height: 512
      format: webp
      compression: true
    - name: test2
      width: 72
      height: 72
      format: webp
      compression: true